name: genreal-ci

trigger:
  - main

variables:
  - group: SonarQube

stages:
  - stage: CODE_QUALITY_CHECK
    displayName: "Code Quality Check"
    jobs:
      - job: environment
        pool:
          vmImage: $(poolvmImage)
      - job: GitCheckout
        steps:
          - checkout: self
            clean: "true"
          - task: Npm@1
            inputs:
              command: "install"
