# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

name: general-ci

variables:
  - group: SonarQube

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Install_NodeJS
    displayName: 'Install NodeJS'
    condition: succeeded()
    jobs:
      - job: Install_Node
        displayName: 'Install Node'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '10.x'
  - stage: Checkout_and_Install
    displayName: 'Checkout and Install'
    condition: succeeded()
    jobs:
      - job: Checkout
        displayName: 'Checkout'
        condition: succeeded()
        steps:
          - checkout: self
            persistCredentials: true
            fetchDepth: 0
  - stage: Run_Code_Analysis_And_Publish
    displayName: 'Analyse Code And Publish'
    jobs:
      - job: SonarAnalyse
        - task: SonarQubeAnalyze@5                                                  # Run Code Analysis after Checkout
          inputs:
            jdkversion: 'JAVA_HOME_17_x64'
      - job: SonarPublish
        - task: SonarQubePublish@5                                                  # Publish Quality Gate Result
          inputs:
            pollingTimeoutSec: '300'
  - stage: Install_Dependencies
    displayName: 'Install Node Dependencies'
    - task: Npm@1
      inputs:
        command: 'install'
        arguments: '--no-audit'