name: genreal-ci

trigger:
  - main

stages:
  - stage: CODE_QUALITY_CHECK
    displayName: "Code Quality Check"
    jobs:
      - job: environment
        pool:
          vmImage: '$(poolvmImage)'
        steps:
          - checkout: self
            clean: "true"
          - task: Npm@1
            inputs:
              command: 'install'
